modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/team-abnormals/upgrade-aquatic/issues"
license = "https://github.com/team-abnormals/upgrade-aquatic/blob/main/LICENSE.txt"

[[mods]]
    modId = "upgrade_aquatic"
    version = "${file.jarVersion}"
    logoFile = "logo.png"
    itemIcon = "upgrade_aquatic:pike"
    configBackground = "upgrade_aquatic:textures/block/coralstone.png"
    authors = "Team Abnormals"
    credits = "SmellyModder, bageldotjpg, Cameron, five, SystemZee, Ocelot, Endergized"
    displayURL = "https://www.teamabnormals.com/mods/upgrade-aquatic"
    displayName = "Upgrade Aquatic"
    description = '''
    Expands upon Update Aquatic and aquatic life as a whole with new enemies, sea creatures, and building blocks.
    '''

[[dependencies.upgrade_aquatic]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.18.2,1.19)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.upgrade_aquatic]]
    modId = "forge"
    mandatory = true
    versionRange = "[40.1.0,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.upgrade_aquatic]]
    modId = "blueprint"
    mandatory = true
    versionRange = "[5.5.0,)"
    ordering = "AFTER"
    side = "BOTH"